# Whenever a push is made to the master branch then run the job
on:
  push:
    branches:
      - 'v*'

jobs:
  # job id, can be anything
  export_game:
    # Always use ubuntu-latest for this action
    runs-on: ubuntu-latest
    # Job name, can be anything
    name: Export Game Job
    steps:
      # Always include the checkout step so that
      # your project is available for Godot to export
    - name: checkout
      uses: actions/checkout@v2.3.1
      # Ensure that you get the entire project history
      with:
        fetch-depth: 0
      # separate step to extract the version from the tag name
    - name: get tag from version
      id: tag_version
      run: |
        echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}
    - name: install wine
      id: wine_install
      run: |
        sudo apt install wine64
        echo ::set-output name=WINE_PATH::$(which wine64)
    - name: export game
      # Use latest version (see releases for all versions)
      uses: firebelley/godot-export@v3.0.0
      with:
        # Defining all the required inputs
        # I used the mono version of Godot in this example
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.3/rc9/mono/Godot_v3.3-rc9_mono_linux_headless_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.3/rc9/mono/Godot_v3.3-rc9_mono_export_templates.tpz
        relative_project_path: ./
        create_release: false
        base_version:  ${{ steps.tag_version.outputs.TAG_VERSION}}
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
